"use strict";

const ERROR_CODES = {
  ERR_INVALID_SSI: "ERR_INVALID_SSI",
  ERR_INVALID_SCOPE: "ERR_INVALID_SCOPE",
  ERR_DOMAIN_MISMATCH: "ERR_DOMAIN_MISMATCH",
  ERR_UNSUPPORTED_VERSION: "ERR_UNSUPPORTED_VERSION",
  ERR_ANCHOR_NOT_FOUND: "ERR_ANCHOR_NOT_FOUND",
  ERR_EVENT_PARSE_FAILED: "ERR_EVENT_PARSE_FAILED",
  ERR_EVENT_SIGNATURE_INVALID: "ERR_EVENT_SIGNATURE_INVALID",
  ERR_EVENT_CHAIN_INVALID: "ERR_EVENT_CHAIN_INVALID",
  ERR_BRICK_NOT_FOUND: "ERR_BRICK_NOT_FOUND",
  ERR_BRICK_HASH_MISMATCH: "ERR_BRICK_HASH_MISMATCH",
  ERR_DECRYPTION_FAILED: "ERR_DECRYPTION_FAILED",
  ERR_ACCESS_DENIED: "ERR_ACCESS_DENIED",
  ERR_READ_ONLY_DSU: "ERR_READ_ONLY_DSU",
  ERR_BATCH_ALREADY_STARTED: "ERR_BATCH_ALREADY_STARTED",
  ERR_NO_BATCH_IN_PROGRESS: "ERR_NO_BATCH_IN_PROGRESS",
  ERR_CONCURRENT_COMMIT: "ERR_CONCURRENT_COMMIT",
  ERR_INVALID_PATH: "ERR_INVALID_PATH",
  ERR_INVALID_PERMISSION: "ERR_INVALID_PERMISSION",
  ERR_INVALID_PROVENANCE_PROFILE: "ERR_INVALID_PROVENANCE_PROFILE",
  ERR_PROVENANCE_VALIDATION_FAILED: "ERR_PROVENANCE_VALIDATION_FAILED",
  ERR_UNSUPPORTED_PROFILE: "ERR_UNSUPPORTED_PROFILE"
};

class LightDSUError extends Error {
  constructor(code, message, details) {
    super(message || code);
    this.name = "LightDSUError";
    this.code = code;
    this.details = details;
  }
}

function throwError(code, message, details) {
  throw new LightDSUError(code, message, details);
}

module.exports = { ERROR_CODES, LightDSUError, throwError };
